// Presentation regressions: safe model text, complete content, citations and framework sections.
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const template = fs.readFileSync('data/preview_template.html', 'utf8');
const context = { fmtRec: () => '1', confLabel: () => 'high' };
vm.createContext(context);
vm.runInContext(template.slice(template.indexOf('  function answerEscape('), template.indexOf('  // 失敗時要講清楚')), context);
vm.runInContext(template.slice(template.indexOf('  function answerMapText('), template.indexOf('  function renderSources(')), context);
const { md, splitLead, markUnverified, linkCites } = context;
const text = '目前無法分配金額。\n\n**主張／決策問題**\n先確認需求。\n\n**證據驗證**\n- 人口 64 人 [1]\n- 缺總預算\n\n**嚴重度比較**\n1. 六都比較\n2. 年度比較\n\n**候選區訊號／行動建議**\n只能提出候選。\n\n**權責與資料缺口**\n不可編造比例。';
const parts = splitLead(text), html = md(parts.rest);
assert.equal(parts.lead, '目前無法分配金額。');
assert.equal((html.match(/class="answer-step"/g) || []).length, 5);
assert.match(html, /<ul><li>人口 64 人 \[1\]<\/li><li>缺總預算<\/li><\/ul>/);
assert.match(html, /<ol start="1"><li>六都比較<\/li><li>年度比較<\/li><\/ol>/);
assert.match(html, /不可編造比例。/);
const dangerous = md('<img src=x onerror="alert(1)"> **正常粗體** & \'');
assert.ok(!dangerous.includes('<img'));
assert.match(dangerous, /&lt;img/);
assert.match(dangerous, /<b>正常粗體<\/b>/);
const records = [{region:'新北市',age_group:'18-35',metric:'人口',provenance:{}}];
const decorated = linkCites(markUnverified(html, ['64']), records);
assert.match(decorated, /<mark class="unv"[^>]*>64<\/mark>/);
assert.match(decorated, /class="citeref" data-i="1"/);
assert.equal(linkCites(markUnverified(dangerous, ['39']), records), dangerous);
const leadText = '完整結論即使很長也不能被刪除。'.repeat(12);
assert.equal(splitLead(leadText+'\n\n**限制**\n資料不足').lead, leadText);
assert.equal(md(leadText).replace(/<[^>]+>/g,''), leadText);
assert.match(splitLead('## 分析\n結論。\n\n**限制**\n資料不足').rest,/## 分析/);
assert.match(template, /id="askMore" aria-expanded="false" aria-controls="askFull"/);
assert.match(template, /\.answer \.full\[hidden\],\.answer-step-body\[hidden\]\{display:block!important;/);
assert.match(html, /aria-expanded="true"[^>]*>主張／決策問題/);
assert.match(html, /aria-expanded="false"[^>]*>證據驗證/);
assert.match(html, /aria-expanded="false"[^>]*>嚴重度比較/);
assert.match(html, /aria-expanded="true"[^>]*>權責與資料缺口/);
assert.equal((html.match(/class="answer-step-body"[^>]* hidden/g)||[]).length, 3);
assert.equal(splitLead('**不建議平均分配。**\n後續分析。').lead, '**不建議平均分配。**');
assert.equal(splitLead('**不建議平均分配。**\n後續分析。').rest, '後續分析。');
const body = { hidden: true }, button = {getAttribute: () => 'answerStep1',setAttribute: (k,v) => button[k]=v};
context.$ = id => { assert.equal(id,'answerStep1'); return body; };
context.toggleAnswerStep(button);
assert.equal(body.hidden,false); assert.equal(button['aria-expanded'],'true');
context.toggleAnswerStep(button);
assert.equal(body.hidden,true); assert.equal(button['aria-expanded'],'false');
assert.match(template, /if \(step\) \{ toggleAnswerStep\(step\); return; \}/);
console.log('Answer presentation: framework, lists, full text, escaping, citations, warnings, print and toggle contracts passed.');
